import jsPDF from 'jspdf'

export function generateFormPDF(form, formData, email) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20
  let y = margin

  // Header bar
  doc.setFillColor(37, 99, 235)
  doc.rect(0, 0, pageWidth, 38, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(form.title, margin, 16)

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text(`Submitted: ${new Date().toLocaleString()}`, margin, 26)
  doc.text(`Copy sent to: ${email}`, margin, 33)

  y = 50
  doc.setTextColor(0, 0, 0)

  form.sections.forEach((section) => {
    if (y > 255) {
      doc.addPage()
      y = margin
    }

    // Section label background
    doc.setFillColor(239, 246, 255)
    doc.rect(margin - 5, y - 5, pageWidth - margin * 2 + 10, 13, 'F')
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(37, 99, 235)
    doc.text(section.name.toUpperCase(), margin, y + 4)
    y += 16

    doc.setTextColor(17, 24, 39)

    section.fields.forEach((field) => {
      if (y > 272) {
        doc.addPage()
        y = margin
      }

      const raw = formData[field.id]
      const display =
        raw !== undefined && raw !== null && raw !== '' ? String(raw) : '—'

      doc.setFontSize(10)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(55, 65, 81)
      doc.text(`${field.name}:`, margin, y)

      doc.setFont('helvetica', 'normal')
      doc.setTextColor(17, 24, 39)

      const maxWidth = pageWidth - margin * 2 - 72
      const lines = doc.splitTextToSize(display, maxWidth)
      doc.text(lines, margin + 70, y)
      y += lines.length > 1 ? lines.length * 6 + 3 : 8
    })

    y += 6
  })

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(156, 163, 175)
  doc.text('Generated by GuestSheet', margin, pageHeight - 10)
  doc.text(
    new Date().toLocaleDateString(),
    pageWidth - margin - 28,
    pageHeight - 10,
  )

  return doc
}
